"""verification jobs + occurrence prompt token

Revision ID: 00cf1f42e2a1
Revises: 6b706f4d7f10
Create Date: 2026-08-28 10:14:10.078684
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '00cf1f42e2a1'
down_revision: str | None = '6b706f4d7f10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['chore_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_jobs_occurrence_id'), 'verification_jobs', ['occurrence_id'], unique=False)
    op.create_index(op.f('ix_verification_jobs_state'), 'verification_jobs', ['state'], unique=False)
    op.add_column('chore_occurrences', sa.Column('prompt_token', sa.String(length=8), nullable=True))
    op.add_column('chore_occurrences', sa.Column('verification_error', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chore_occurrences', 'verification_error')
    op.drop_column('chore_occurrences', 'prompt_token')
    op.drop_index(op.f('ix_verification_jobs_state'), table_name='verification_jobs')
    op.drop_index(op.f('ix_verification_jobs_occurrence_id'), table_name='verification_jobs')
    op.drop_table('verification_jobs')
    # ### end Alembic commands ###
