"""weekend due time

Optional Saturday/Sunday wall-clock time on a chore (spec §4.1). Nullable with no
backfill: NULL means "due_time every day", which is exactly how every existing chore
already behaves.

Revision ID: 11b3a908ec95
Revises: 611e51699760
Create Date: 2026-09-23 16:16:22.924730
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '11b3a908ec95'
down_revision: str | None = '611e51699760'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('weekend_due_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chores', 'weekend_due_time')
    # ### end Alembic commands ###
