"""phase9 manual penalties

Revision ID: 410442991126
Revises: 9c1e4b0a7d21
Create Date: 2026-09-01 18:30:20.380012
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '410442991126'
down_revision: str | None = '9c1e4b0a7d21'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('chore_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ledger_entries_chore_id'), 'ledger_entries', ['chore_id'], unique=False)
    # Named explicitly: Postgres would auto-name it, and downgrade() has to drop it by name.
    op.create_foreign_key(
        "fk_ledger_entries_chore_id_chores",
        "ledger_entries",
        "chores",
        ["chore_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_ledger_entries_chore_id_chores", "ledger_entries", type_="foreignkey")
    op.drop_index(op.f('ix_ledger_entries_chore_id'), table_name='ledger_entries')
    op.drop_column('ledger_entries', 'chore_id')
    # ### end Alembic commands ###
