"""phase4 drop verification rule

verification_rule was never sent to the model as itself. worker/verify.py only ever used it
as a fallback when the checklist was empty, converting it into a single required check —
and silently ignored it the moment a checklist existed. Two fields, one of which quietly
discarded the parent's typing.

The upgrade does that same conversion once, permanently, so a chore that had only a rule
keeps verifying exactly as it did. Without it those chores would reach the model with no
checks at all, which derive_verdict resolves to NEEDS_REVIEW every time — an llm_auto chore
would silently stop paying out.

Note the checklist column can hold a JSON `null` as well as SQL NULL, so the backfill tests
for both.

Revision ID: 4275043873ad
Revises: 86f384ed91a5
Create Date: 2026-09-01 06:59:45.762297
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4275043873ad'
down_revision: str | None = '86f384ed91a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chores', 'chore_kind',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chores', 'standing_on',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # Backfill before dropping: rule -> the single required check it already behaved as.
    op.execute(
        """
        UPDATE chores
           SET verification_checklist =
               jsonb_build_array(
                   jsonb_build_object(
                       'id', 1,
                       'text', verification_rule,
                       'required', true
                   )
               )
         WHERE verification_rule IS NOT NULL
           AND verification_rule <> ''
           AND (
                verification_checklist IS NULL
                -- covers a JSON `null` and any non-array scalar; jsonb_array_length would
                -- raise on those, and OR is not guaranteed to short-circuit.
                OR jsonb_typeof(verification_checklist) <> 'array'
                OR verification_checklist = '[]'::jsonb
               )
        """
    )
    op.drop_column('chores', 'verification_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The column comes back empty: the rules now live on as checklist items, and guessing
    # which check was once a rule would be worse than leaving it NULL.
    op.add_column(
        'chores', sa.Column('verification_rule', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.alter_column('chores', 'standing_on',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('chores', 'chore_kind',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'scheduled'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
