"""phase6 scheduler heartbeat

Revision ID: 496ac0c86427
Revises: 410442991126
Create Date: 2026-09-02 15:28:55.086612
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '496ac0c86427'
down_revision: str | None = '410442991126'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_settings', sa.Column('last_scheduler_tick_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_settings', 'last_scheduler_tick_at')
    # ### end Alembic commands ###
