"""phase6 media thumbnail retention columns

Revision ID: 49fe958ee186
Revises: 65d7e93654ba
Create Date: 2026-08-28 12:04:30.617824
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '49fe958ee186'
down_revision: str | None = '65d7e93654ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_media', sa.Column('thumbnail_path', sa.String(length=255), nullable=True))
    op.add_column('submission_media', sa.Column('original_deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_media', 'original_deleted_at')
    op.drop_column('submission_media', 'thumbnail_path')
    # ### end Alembic commands ###
