"""drop prompt token

Revision ID: 4d0412d19f5a
Revises: 79278d56165b
Create Date: 2026-08-31 15:32:23.945775
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4d0412d19f5a'
down_revision: str | None = '79278d56165b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chore_occurrences', 'prompt_token')
    op.drop_column('chores', 'prompt_token_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so the NOT NULL column can be added back to a populated table.
    op.add_column(
        'chores',
        sa.Column(
            'prompt_token_enabled',
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column('chore_occurrences', sa.Column('prompt_token', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
