"""phase6 household settings for llm config

Revision ID: 52e593725271
Revises: 49fe958ee186
Create Date: 2026-08-28 14:13:00.785875
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '52e593725271'
down_revision: str | None = '49fe958ee186'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('llm_base_url', sa.String(length=255), nullable=True),
    sa.Column('llm_model', sa.String(length=160), nullable=True),
    sa.Column('llm_api_key', sa.Text(), nullable=True),
    sa.Column('llm_timeout_s', sa.Integer(), nullable=True),
    sa.Column('llm_max_retries', sa.Integer(), nullable=True),
    sa.Column('auto_pass_threshold', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('auto_fail_threshold', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('household_settings')
    # ### end Alembic commands ###
