"""phase8 missed settlement

Revision ID: 563533ab7236
Revises: 4275043873ad
Create Date: 2026-09-01 13:07:46.803174
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '563533ab7236'
down_revision: str | None = '4275043873ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore_occurrences', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chore_occurrences', 'settled_at')
    # ### end Alembic commands ###
