"""push ttl and per-device counts

Revision ID: 611e51699760
Revises: 996867efb591
Create Date: 2026-09-07 14:24:42.090545
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '611e51699760'
down_revision: str | None = '996867efb591'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_log', sa.Column('devices', sa.Integer(), nullable=True))
    op.add_column('notification_log', sa.Column('delivered', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_log', 'delivered')
    op.drop_column('notification_log', 'devices')
    # ### end Alembic commands ###
