"""chores and occurrences

Revision ID: 6a5a54a2203a
Revises: afc0f5474cb5
Create Date: 2026-08-28 09:30:04.487202
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6a5a54a2203a'
down_revision: str | None = 'afc0f5474cb5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignment_mode', sa.String(length=16), nullable=False),
    sa.Column('fixed_assignee_id', sa.UUID(), nullable=True),
    sa.Column('assignee_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('rotation_period', sa.String(length=16), nullable=True),
    sa.Column('rotation_anchor_date', sa.Date(), nullable=True),
    sa.Column('cadence', sa.String(length=120), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=False),
    sa.Column('window_open_offset_s', sa.Integer(), nullable=False),
    sa.Column('grace_period_s', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('proof_type', sa.String(length=24), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('photo_prompts', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('allow_gallery_upload', sa.Boolean(), nullable=False),
    sa.Column('prompt_token_enabled', sa.Boolean(), nullable=False),
    sa.Column('geofence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_mode', sa.String(length=16), nullable=False),
    sa.Column('verification_rule', sa.Text(), nullable=True),
    sa.Column('verification_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_pass_threshold', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('auto_fail_threshold', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('reward_cents', sa.Integer(), nullable=False),
    sa.Column('penalty_cents', sa.Integer(), nullable=False),
    sa.Column('late_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixed_assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chores_active'), 'chores', ['active'], unique=False)
    op.create_index(op.f('ix_chores_household_id'), 'chores', ['household_id'], unique=False)
    op.create_table('chore_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('chore_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('window_open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('was_late', sa.Boolean(), nullable=False),
    sa.Column('settlement_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_cents', sa.Integer(), nullable=False),
    sa.Column('penalty_cents', sa.Integer(), nullable=False),
    sa.Column('late_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chore_id', 'due_at', 'assignee_id', name='uq_occurrence_slot')
    )
    op.create_index(op.f('ix_chore_occurrences_chore_id'), 'chore_occurrences', ['chore_id'], unique=False)
    op.create_index(op.f('ix_chore_occurrences_due_at'), 'chore_occurrences', ['due_at'], unique=False)
    op.create_index(op.f('ix_chore_occurrences_household_id'), 'chore_occurrences', ['household_id'], unique=False)
    op.create_index('ix_occurrence_assignee_due', 'chore_occurrences', ['assignee_id', 'due_at'], unique=False)
    op.create_index('ix_occurrence_status_due', 'chore_occurrences', ['status', 'due_at'], unique=False)
    op.create_index('uq_occurrence_unassigned_slot', 'chore_occurrences', ['chore_id', 'due_at'], unique=True, postgresql_where=sa.text('assignee_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_occurrence_unassigned_slot', table_name='chore_occurrences', postgresql_where=sa.text('assignee_id IS NULL'))
    op.drop_index('ix_occurrence_status_due', table_name='chore_occurrences')
    op.drop_index('ix_occurrence_assignee_due', table_name='chore_occurrences')
    op.drop_index(op.f('ix_chore_occurrences_household_id'), table_name='chore_occurrences')
    op.drop_index(op.f('ix_chore_occurrences_due_at'), table_name='chore_occurrences')
    op.drop_index(op.f('ix_chore_occurrences_chore_id'), table_name='chore_occurrences')
    op.drop_table('chore_occurrences')
    op.drop_index(op.f('ix_chores_household_id'), table_name='chores')
    op.drop_index(op.f('ix_chores_active'), table_name='chores')
    op.drop_table('chores')
    # ### end Alembic commands ###
