"""submissions, verifications, ledger

Revision ID: 6b706f4d7f10
Revises: 6a5a54a2203a
Create Date: 2026-08-28 09:55:43.576934
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6b706f4d7f10'
down_revision: str | None = '6a5a54a2203a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=8), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('reversed_by_entry_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['chore_occurrences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_entry_id'], ['ledger_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_child', 'ledger_entries', ['child_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_household_id'), 'ledger_entries', ['household_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_occurrence_id'), 'ledger_entries', ['occurrence_id'], unique=False)
    op.create_index('uq_ledger_occurrence_earn_kind', 'ledger_entries', ['occurrence_id', 'kind'], unique=True, postgresql_where=sa.text("kind IN ('earning','penalty')"))
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('submitter_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('client_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('geo_lat', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('geo_lon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('geo_accuracy_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('geo_distance_m', sa.Numeric(precision=9, scale=1), nullable=True),
    sa.Column('geo_within', sa.Boolean(), nullable=True),
    sa.Column('geo_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['chore_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_occurrence_id'), 'submissions', ['occurrence_id'], unique=False)
    op.create_table('submission_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('prompt_label', sa.String(length=120), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=40), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('exif', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'idx', name='uq_submission_media_idx')
    )
    op.create_index(op.f('ix_submission_media_phash'), 'submission_media', ['phash'], unique=False)
    op.create_index(op.f('ix_submission_media_sha256'), 'submission_media', ['sha256'], unique=False)
    op.create_index(op.f('ix_submission_media_submission_id'), 'submission_media', ['submission_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('child_message', sa.Text(), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_quality_issue', sa.String(length=24), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=8), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['chore_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_occurrence_id'), 'verifications', ['occurrence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_occurrence_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_submission_media_submission_id'), table_name='submission_media')
    op.drop_index(op.f('ix_submission_media_sha256'), table_name='submission_media')
    op.drop_index(op.f('ix_submission_media_phash'), table_name='submission_media')
    op.drop_table('submission_media')
    op.drop_index(op.f('ix_submissions_occurrence_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('uq_ledger_occurrence_earn_kind', table_name='ledger_entries', postgresql_where=sa.text("kind IN ('earning','penalty')"))
    op.drop_index(op.f('ix_ledger_entries_occurrence_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_household_id'), table_name='ledger_entries')
    op.drop_index('ix_ledger_child', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
