"""phase4 standing chores

A chore is now either a recurring rule or a state a parent flips (spec §4.7).

The two NOT NULL columns carry a server_default so the DDL succeeds against a table that
already has rows — autogenerate omits it, and without it this migration fails on any
existing install. Every existing chore becomes scheduled/off, which is exactly right.

Revision ID: 86f384ed91a5
Revises: b8c234906aed
Create Date: 2026-08-31 20:10:44.867830
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '86f384ed91a5'
down_revision: str | None = 'b8c234906aed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore_state_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('chore_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('tier', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chore_state_chore_created', 'chore_state_events', ['chore_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chore_state_events_chore_id'), 'chore_state_events', ['chore_id'], unique=False)
    op.create_index(op.f('ix_chore_state_events_household_id'), 'chore_state_events', ['household_id'], unique=False)
    op.add_column(
        'chores',
        sa.Column(
            'chore_kind', sa.String(length=16), nullable=False, server_default='scheduled'
        ),
    )
    op.add_column(
        'chores',
        sa.Column('standing_on', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('chores', sa.Column('standing_tier_id', sa.Integer(), nullable=True))
    op.add_column('chores', sa.Column('standing_since', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chores_chore_kind'), 'chores', ['chore_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chores_chore_kind'), table_name='chores')
    op.drop_column('chores', 'standing_since')
    op.drop_column('chores', 'standing_tier_id')
    op.drop_column('chores', 'standing_on')
    op.drop_column('chores', 'chore_kind')
    op.drop_index(op.f('ix_chore_state_events_household_id'), table_name='chore_state_events')
    op.drop_index(op.f('ix_chore_state_events_chore_id'), table_name='chore_state_events')
    op.drop_index('ix_chore_state_chore_created', table_name='chore_state_events')
    op.drop_table('chore_state_events')
    # ### end Alembic commands ###
