"""phase4 outcome tiers

Condition -> outcome tiers for chores a person grades (spec §4.6). Every column is
nullable with no backfill: an existing chore has no tiers and keeps its
reward_cents/penalty_cents behaviour untouched. chore_occurrences snapshots the tier
list at generation for the same reason it snapshots the money terms (spec §3).

Revision ID: b8c234906aed
Revises: 4d0412d19f5a
Create Date: 2026-08-31 19:55:11.602027
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b8c234906aed'
down_revision: str | None = '4d0412d19f5a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore_occurrences', sa.Column('outcome_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chore_occurrences', sa.Column('outcome_tier_id', sa.Integer(), nullable=True))
    op.add_column('chore_occurrences', sa.Column('outcome_tier', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chores', sa.Column('outcome_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chores', 'outcome_tiers')
    op.drop_column('chore_occurrences', 'outcome_tier')
    op.drop_column('chore_occurrences', 'outcome_tier_id')
    op.drop_column('chore_occurrences', 'outcome_tiers')
    # ### end Alembic commands ###
