"""phase8 reminder marker

Revision ID: be8bfa6f021d
Revises: 496ac0c86427
Create Date: 2026-09-03 18:58:07.745849
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'be8bfa6f021d'
down_revision: str | None = '496ac0c86427'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore_occurrences', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chore_occurrences', 'reminder_sent_at')
    # ### end Alembic commands ###
