"""checkin tokens

Revision ID: d38434040817
Revises: 00cf1f42e2a1
Create Date: 2026-08-28 10:47:34.004327
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd38434040817'
down_revision: str | None = '00cf1f42e2a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkin_tokens_child_id'), 'checkin_tokens', ['child_id'], unique=True)
    op.create_index(op.f('ix_checkin_tokens_token'), 'checkin_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkin_tokens_token'), table_name='checkin_tokens')
    op.drop_index(op.f('ix_checkin_tokens_child_id'), table_name='checkin_tokens')
    op.drop_table('checkin_tokens')
    # ### end Alembic commands ###
